### ISSUE TITLE
url not working for texture rendering

### ISSUE THREAD

**Issue by hpicsk** [xch-liu/learning-warp-st#3]
URL for downloading the model for texture rendering does not work

**Comment by Rem-Yin** [comment]
Anyone downloaded before? I REALLY need model.

**Comment by xch-liu** [comment]
I have updated the link, please try this: https://web.eecs.umich.edu/~justincj/models/vgg19-d01eb7cb.pth

**Comment by Rem-Yin** [comment]
Got it! Thanks a lot!!
